name = "AutomationLabsExportationController"
uuid = "f62be0fb-3d92-41bb-8127-f55377692a9d"
authors = ["Pierre BLAUD <pierre.blaud@ikmail.com> and contributors"]
version = "0.1.0"

[deps]
AutomationLabsModelPredictiveControl = "731a2950-2bc0-4254-a525-a4bb07017e97"
AutomationLabsSystems = "6d3dfdf0-e107-48c6-a6ff-eced1a5a9334"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
